name: Aliyun Signin

on:
 schedule:
  #每天国际时间17:20 运行一次
  - cron:'20 17 * * *'
 workflow_dispatch:
jobs:
 signin:
  name: Aliyun Signin
  runs-on: ubuntu-latest
  steps :
   -uses: ImYrS/aliyun-auto-signin@main
    with:
      REFRESH_ TOKENS: ${{ secrets.REFRESH_TOKENS }}
      GP_ TOKEN: ${{ secrets.GP_TOKEN}}
      PUSH_TYPES: 'TELEGRAM'
      TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
      TELEGRAM_CHАT_ID: ${{ secrets.TELEGRAM_CHAT_ID }} 
